### ISSUE TITLE
contribuidores 

### ISSUE THREAD

**Issue by jonatasosilva** [projeto-hacktoberfest/testes#2]
@all-contributors add @jonatasosilva

**Comment by jonatasosilva** [comment]
@all-contributors please add @jonatas for contributions

**Comment by jonatasosilva** [comment]
@all-contributors add @jonatasosilva for code

**Comment by daviosilva** [comment]
@all-contributors add @daviosilva

**Comment by daviosilva** [comment]
@all-contributors add @daviosilva for doc
